const SET_POSTS = "SET_POSTS";
const SET_CURRENT_POST = "SET_CURRENT_POST";
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";

export const actionTypes = {
  SET_POSTS,
  SET_CURRENT_POST,
  FETCH_ALL_POSTS,
};
