const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
const FETCH_ONE_POST = "FETCH_ONE_POST";
const CREATE_POST = "CREATE_POST";
const UPDATE_POST = "UPDATE_POST";
const DELETE_POST = "DELETE_POST";

export const actionTypes = {
  FETCH_ALL_POSTS,
  FETCH_ONE_POST,
  CREATE_POST,
  UPDATE_POST,
  DELETE_POST,
};
