const FETCH_ALL_COMMENTS = "FETCH_ALL_COMMENTS";
const CREATE_COMMENT = "CREATE_COMMENT";
const UPDATE_COMMENT = "UPDATE_COMMENT";
const DELETE_COMMENT = "DELETE_COMMENT";

export const actionTypes = {
  FETCH_ALL_COMMENTS,
  CREATE_COMMENT,
  UPDATE_COMMENT,
  DELETE_COMMENT,
};
