const SET_CURRENT_USER = "SET_CURRENT_USER";
const SET_VIEWED_USER = "SET_VIEWED_USER";
const SET_USERS = "SET_USERS";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";

export const actionTypes = {
  SET_CURRENT_USER,
  SET_VIEWED_USER,
  SET_USERS,
  FETCH_ALL_USERS,
};
