const SHOW_LOADER = "SHOW_LOADER";
const HIDE_LOADER = "HIDE_LOADER";
const SHOW_ALERT = "SHOW_ALERT";
const HIDE_ALERT = "SUCCESS_HIDE_ALERT";
export const actionTypes = {
  SHOW_LOADER,
  HIDE_LOADER,
  SHOW_ALERT,
  HIDE_ALERT,
};
